version: "3.9"

services:
  deepstack:
    image: "deepquestai/deepstack:gpu"
    ports:
      - "5555:5000"
    volumes:
      - $INSTALL_DIR/deepstack:/datastore
    environment:
      - VISION-FACE=True
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
