version: "3.9"

networks:
  gateway:
    external: true
    name: gateway

services:
  deepstack:
    image: "deepquestai/deepstack:gpu"
    volumes:
      - $INSTALL_DIR/datastore:/datastore
    environment:
      - VISION-FACE=True
    networks:
      - gateway
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
