services:
  deepstack:
    container_name: deepstack
    image: "deepquestai/deepstack:gpu"
    ports:
      - "5555:5000"
    volumes:
      - $INSTALL_DIR/deepstack:/datastore
    environment:
      - VISION-FACE=True
    restart: unless-stopped
    runtime: nvidia
    deploy:
      resources:
        reservations:
          devices:
            - capabilities: [gpu]
    logging:
      driver: syslog
      options:
        syslog-address: udp://172.16.20.11:7514
        syslog-format: "rfc3164"
        tag: "deepstack"
